import 'dart:io';
import 'package:csv/csv.dart';
import 'package:file_picker/file_picker.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import '../models/issue_model.dart';
import '../models/user_model.dart'; // import User model

class ExportService {
  static Future<void> exportToCsv(List<Issue> issues) async {
    List<List<dynamic>> rows = [];
    rows.add([
      "S.No",
      "Date",
      "Name",
      "Emp No",
      "Problem",
      "Sorted?",
      "Materials Replaced",
      "Attended By"
    ]);

    for (var issue in issues) {
      rows.add([
        issue.sno,
        DateFormat('yyyy-MM-dd').format(issue.date),
        issue.name,
        issue.empNo,
        issue.problem,
        issue.isIssueSorted ? "Yes" : "No",
        issue.materialsReplaced,
        issue.attendedBy
      ]);
    }

    String csv = const ListToCsvConverter().convert(rows);

    String? outputFile = await FilePicker.platform.saveFile(
      dialogTitle: 'Save CSV',
      fileName:
          'barcf_reports_${DateFormat('yyyyMMdd_HHmm').format(DateTime.now())}.csv',
      allowedExtensions: ['csv'],
      type: FileType.custom,
    );

    if (outputFile != null) {
      // file_picker might return path without extension in some cases on Windows?
      if (!outputFile.endsWith('.csv')) outputFile += '.csv';
      final file = File(outputFile);
      await file.writeAsString(csv);
    }
  }

  static Future<void> exportToPdf(List<Issue> issues, User user) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('BARCF Reports',
                      style: pw.TextStyle(
                          fontSize: 24, fontWeight: pw.FontWeight.bold)),
                  pw.Text(
                      'Generated by: ${user.username} on ${DateFormat('yyyy-MM-dd').format(DateTime.now())}'),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Table.fromTextArray(
              context: context,
              data: <List<String>>[
                <String>[
                  'S.No',
                  'Date',
                  'Name',
                  'Prob',
                  'Status',
                  'Attended By'
                ],
                ...issues.map((issue) => [
                      issue.sno?.toString() ?? '',
                      DateFormat('yyyy-MM-dd').format(issue.date),
                      issue.name,
                      issue.problem.length > 20
                          ? '${issue.problem.substring(0, 20)}...'
                          : issue.problem,
                      issue.isIssueSorted ? 'Yes' : 'No',
                      issue.attendedBy,
                    ]),
              ],
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => doc.save(),
      name: 'BARCF_Report_${DateFormat('yyyyMMdd').format(DateTime.now())}',
    );
  }
}
